name: project_manager
description: project_manager is a CLI tool for creating boilerplate code for the flutter project. It supports BLoC, Riverpod, and MobX state management library. You can create a production-ready boilerplate app with just one command using project_manager.
version: 0.0.1-beta.2
homepage: https://github.com/parthp-7span/project-manager

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  args: ^2.3.1
  logging: ^1.0.2
  path: ^1.8.1
  meta: ^1.7.0
  interact: ^2.1.1
  logger: ^1.1.0
  mustache_template: ^2.0.0

#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

executables:
  seven: project_manager
