name: project_manager
description: A sample command-line application.
version: 0.0.1-beta.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  args: ^2.3.1
  logging: ^1.0.2
  path: ^1.8.1
  meta: ^1.7.0

#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

executables:
  seven: project_manager
